operator_map = {
    "AcegasApsAmga Spa": ['Acegas APS', 'Acegas Aps'],
    'AMAIE SPA': ['Aamaie'],
    'ARETI SPA': ['Areti'],
    "ASM Vercelli spa": [],
    'Assem SPA': ['Assem'],
    "Azienda Intercomunale Rotaliana Spa - SB": [],
    'AZIENDA RETI ELETTRICHE SRL': ['A2A', 'A2A Reti Elettriche'],
    "AZIENDA SPECIALIZZATA SETTORE MULTISERVIZI S.P.A.": [],
    "Dea Spa": [],
    "DEVAL": ['Deval'],
    "DISTRIBUZIONE ELETTRICA ADRIATICA SRL": [],
    'e-distribuzione S.p.A.': ['Enel Distribuzione S.p.a.', 'E-Distribuzione S.p.A.', 'Enel', 'EnelProduzione', 'ENEL', 'Enel Distribuzione SPA', 'Enel Distribuzione', 'e-distribuzione'],
    "EDYNA SRL": ['EDYNA'],
    "E.U.M. SOC. COOP. PER L'ENERGIA E L'AMBIENTE MOSO S.C.R.L.": ['Eum'],
    "INRETE Distribuzione Energia S.p.A.": ['INRETE S.p.A.'],
    'Terni Distribuzione Elettrica': ['ASM Terni'],
    'Ireti spa': ['IRETI'],
    "LD RETI S.R.L.": [],
    "RetiPiù Srl": [],
    "SECAB SOCIETÀ COOPERATIVA": [],
    "SET DISTRIBUZIONE": ['SET Distribuzione', 'Set Distribuzione', 'SET'],
    "Società Cooperativa Elettrica di Distribuzione Campo Tures": ['Azienda Comunale Campo Tures'],
    'Unareti S.p.A.': ['Unareti S.p.A.','Unareti'],
    'ASM Bressanone S.p.A.': ['ASM Bressanone Spa'],
    'V-RETI': [],
}